require:
  - rubocop-rails

# TODO: update reference once merged.
inherit_from:
  - https://raw.githubusercontent.com/ualbertalib/library_applications_development_inclusive_language/cds/initial-commit/inclusive_language_rubocop.yml

# Exclude checking for the term 'dummy' here as it is included in the Rails generator.
Naming/InclusiveLanguage:
  Exclude:
    - 'test/dummy/**/*'
